/**
 * @package      pkg_projectknife
 * @subpackage   lib_projectknife
 *
 * @author       Tobias Kuhn (eaxs)
 * @copyright    Copyright (C) 2015-2016 Tobias Kuhn. All rights reserved.
 * @license      GNU General Public License version 2 or later.
 */


PKGrid=window.PKGrid||{},PKGrid.show=function(a){var b="undefined"!=typeof a?jQuery(a):jQuery("#adminForm");if(0==b.length)return void console.log("PKGrid.show - Form not found!");var c=jQuery("#grid-select-all",b);c.length&&c.show();var d=jQuery("button.grid-select-item",b);d.length&&d.slideDown(200)},PKGrid.hide=function(a,b){var c="undefined"!=typeof a?jQuery(a):jQuery("#adminForm");if(b="undefined"==typeof b||b,0==c.length)return void console.log("PKGrid.hide - Form not found!");var d=jQuery("#grid-select-all",c);d.length&&d.hide();var e=jQuery("button.grid-select-item",c);e.length&&e.hide(),b&&PKGrid.selectNone(a)},PKGrid.selectAll=function(a){var a="undefined"!=typeof fid?jQuery(fid):jQuery("#adminForm");if(0==a.length)return void console.log("PKGrid.selectAll - Form not found!");var b=jQuery("#grid-select-all",a);b.length&&(b.addClass("btn-success"),b.val(1));var c=jQuery('input[name|="cid[]"]',a);c.length&&c.prop("checked",!0),b=jQuery("button.grid-select-item",a),b.length&&b.addClass("btn-success"),b=jQuery("#boxchecked",a),b.length&&(b.val(c.length),b.trigger("change"))},PKGrid.selectNone=function(a){var b="undefined"!=typeof a?jQuery(a):jQuery("#adminForm");if(0==b.length)return void console.log("PKGrid.selectNone - Form not found!");var c=jQuery('input[name|="cid[]"]',b);c.length&&c.prop("checked",!1),c=jQuery("button.grid-select-item",b),c.length&&c.removeClass("btn-success"),c=jQuery("#grid-select-all",b),c.length&&(c.removeClass("btn-success"),c.val(0)),c=jQuery("#boxchecked",b),c.length&&(c.val(0),c.trigger("change"))},PKGrid.toggleSelectAll=function(a){var b="undefined"!=typeof a?jQuery(a):jQuery("#adminForm");if(0==b.length)return void console.log("PKGrid.toggleSelectAll - Form not found!");var c=jQuery("#grid-select-all",b);c.length&&("1"==c.val()?PKGrid.selectNone(a):PKGrid.selectAll(a))},PKGrid.toggleSelectItem=function(a,b){var c="undefined"!=typeof b?jQuery(b):jQuery("#adminForm");if(0==c.length)return void console.log("PKGrid.toggleSelectItem - Form not found!");var d=jQuery("#cb"+a,c),e=jQuery("#boxchecked",c),f=jQuery("#grid-select-"+a,c);if(d.length&&f.length){d.is(":checked")?(f.removeClass("btn-success"),d.prop("checked",!1),e.length&&e.val(parseInt(e.val())-1)):(f.addClass("btn-success"),d.prop("checked",!0),e.length&&e.val(parseInt(e.val())+1));var g=jQuery("#grid-select-all",c),h=jQuery('input[name|="cid[]"]',c).length;g.length&&h&&e.length&&(h==parseInt(e.val())&&"0"==g.val()?(g.addClass("btn-success"),g.val(1)):h>parseInt(e.val())&&"1"==g.val()&&(g.removeClass("btn-success"),g.val(0))),e.length&&e.trigger("change")}};
